### ISSUE TITLE
Issue (ptxas error) running any sample on Linux (Ubuntu 24.10 on RTX 4070 550 driver)..

### ISSUE THREAD

**Issue by oscarbg** [ingowald/pynari#6]
Hi,
just testing on Windows went ok.. 
but on ubuntu 24.10, python 3.12, RTX4070 I get:

> python sample01.py 
```
#pynari: selecting 'barney' backend
unknown CUDA error when building module for bounds program kernel CUDA_ERROR_UNSUPPORTED_PTX_VERSION log: ptxas application ptx input, line 9; fatal   : Unsupported .version 8.5; current version is '8.4'
Traceback (most recent call last):
  File "/home/osqui/pynari/pynari/sample01.py", line 38, in <module>
    camera = device.newCamera('perspective')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

it's because  I'm on  NVIDIA 550.40.82 dev driver and not latest 565.xx driver?
```
glxinfo
GL_RENDERER   = NVIDIA GeForce RTX 4070/PCIe/SSE2
GL_VERSION    = 4.6.0 NVIDIA 550.40.82
```

I put cuda 12.6.x sdk in path but still error exists:
>export PATH=/usr/local/cuda/bin:$PATH
> ptxas --version
```
ptxas: NVIDIA (R) Ptx optimizing assembler
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Oct_29_23:47:06_PDT_2024
Cuda compilation tools, release 12.6, V12.6.85
Build cuda_12.6.r12.6/compiler.35059454_0
```

**Comment by ingowald** [comment]
Yes that means I built latest module on a newer driver than yours. I thought I'd already fixed that version check, but maybe only for 8.x versions. I'll have a look tomorrow, should be an easy fix. Thx for reporting!

**Comment by ingowald** [comment]
to be a bit more correct in what i said above: the problem is that i'm building on a _CUDA_ version that's newer than what your driver knows - I just checked, and in my local docker image i'm building with cuda 12.6, which is very new, and reports a PTX version that your driver doesn't understand. That's a totally imagined problem - the PTX for embedded programs isn't that depenent on the CUDA version at all - but i'll have to rebuild with an older cuda version. Mea culpa, I should have thought of this. Takes a while to rebuild, i'll upload later today.

**Comment by ingowald** [comment]
just uploaded 1.0.39, that has been built with cuda 12.4 instead of 12.6 - that should work. pls let me know if not.
